### ISSUE TITLE
small mobile responsive issues

### ISSUE THREAD

**Issue by bluedrops** [ReflectionsProjections/rp2017#11]
todo:
- on medium-size devices, the logo overlaps with "reflections" ever so slightly
- some text needs to be modified to be non-breaking spaces for certain screen sizes
- figure out a way to display some sort of title or abbreviation on mobile devices

i'm pretty busy this weekend so if anyone wants to tackle any of these, please do! otherwise I can do them once I finish my exams next week

**Comment by sskhandek** [comment]
@bluedrops taking a pass on this
