### ISSUE TITLE
TODO: Configure React Router for the R|P homepage

### ISSUE THREAD

**Issue by bluedrops** [ReflectionsProjections/rp2017#18]
Create the route reflectionsprojections.com/#/home so we can begin scaffolding out & developing the full site (speakers, events, etc etc.)

Once the site is complete we'll replace reflectionsprojections.com with /home.

**Comment by bluedrops** [comment]
i'll take care of this actually

**Comment by pranaygp** [comment]
@bluedrops we should probably remove "Help Wanted" for ambiguity. Also, this seems like very high priority (in anticipation for webmonkeys tomorrow). Would you be able to do it by then? If not, assign it to me and I'll take care of it by then. I'm sort free tomorrow :)

**Comment by bluedrops** [comment]
o I finished this already; just forgot to close HEH

**Comment by pranaygp** [comment]
:tada:
