### ISSUE TITLE
Include fonts & colors & logo assets in project

### ISSUE THREAD

**Issue by sskhandek** [ReflectionsProjections/rp2017#2]
I'd recommend we put this information inside of the README for the repo

**Comment by warut-vijit** [comment]
@bluedrops you probably know more about the frontend for this site than the rest of us

**Comment by sskhandek** [comment]
@warut-vijit We probably need designer input here

**Comment by bluedrops** [comment]
yeah uh i have no clue, duke
the designer chooses the fonts and colors and logo assets and i just make it happen :^)

**Comment by sskhandek** [comment]
Once all those things are included in this project, I'll close this issue

**Comment by sskhandek** [comment]
@warut-vijit can you add all the info from the design doc you uploaded to the README? It'll make things easier to read and reference when we scaffold the project.

**Comment by maxwellyou-ng** [comment]
I added fonts & colors to the design doc, as well as linking to the drive folder where the most current version of the style guide will reside
