### ISSUE TITLE
Frameworks & Libraries (Discussion)

### ISSUE THREAD

**Issue by sskhandek** [ReflectionsProjections/rp2017#3]
Let's keep external frameworks to a minimum. Here are some initial thoughts:

- We can use React since it's really maintainable and modular, but it might be overkill. 
- Sass might be cool
- We might not need a grid system since flexbox is nice

**Comment by bluedrops** [comment]
oh

**Comment by bluedrops** [comment]
i already made the landing page in angular2 :^) but it'll be easy to port to other things honestly so pick whatever we wanna use

**Comment by sskhandek** [comment]
Sounds good. I guess my point with the react point was questioning whether a framework was necessary at all since it's just a static page, but you make calls, boss ;)

**Comment by bluedrops** [comment]
yeeee; angular2 is probably also overkill tbh but it comes with a router out-of-box; shivali mentioned today that we might need separate subpages for events/speakers this year so i'd like to use a framework so we get those nice seamless partial injections :ok_hand:

**Comment by bluedrops** [comment]
one thing i will say though is that angular2 uses typescript; i think i personally prefer typescript but it's not as beginner friendly in case anyone else wanted to contribute... 

... but also i don't envision the r|p website needing a lot of javascript sooo iunno

**Comment by bluedrops** [comment]
we react now fam
