### ISSUE TITLE
Mobile: Title Disappears

### ISSUE THREAD

**Issue by sskhandek** [ReflectionsProjections/rp2017#9]
On mobile, there's no title for the site!

<img width="379" alt="screen shot 2017-04-03 at 9 17 57 am" src="https://cloud.githubusercontent.com/assets/5349493/24613646/82a7f4aa-184e-11e7-91ad-e71c5df2368c.png">

**Comment by bluedrops** [comment]
u rite
this was an intentional design choice that was probably mistaken
we'll swap in a mobile logo with "r | p" under it soon
